In [1]:
# 분석 전체 과정을 간단하게 진행

In [21]:
# 자주 쓰는 라이브러리들
# 기본
import pandas as pd
import numpy as np
import scipy.stats as ss
import sklearn
# 정제용
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn import feature_selection
from sklearn import feature_extraction
from sklearn import metrics
from sklearn.model_selection import train_test_split
# 학습용 - 분류
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
# 학습용 - 회귀
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
# 평가
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
df = pd.read_csv('C:/Engineer_Big_Data_Analysis/DATAS/이기적데이터/iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
display(df.info())
df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


None

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [6]:
# 범주형인 species 의 값을 숫자로 바꾸기
# replace 이용
df.species.replace({'setosa':0, 'versicolor':1, 'virginica':2}, inplace=True)
df.species.unique()

array([0, 1, 2], dtype=int64)

In [10]:
# 데이터셋 준비 및 분할
X = df.loc[:, 'sepal_length':'petal_width']
Y = df.loc[:, 'species']
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=311)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(120, 4) (120,)
(30, 4) (30,)


In [12]:
# model 정의
cl = DecisionTreeClassifier(random_state=311)
# 학습
cl.fit(x_train, y_train)

DecisionTreeClassifier(random_state=311)

In [18]:
# 예측 수행
y_pred = cl.predict(x_test)
print(pred)

[0 2 1 2 0 0 2 2 2 1 2 2 2 2 1 0 0 0 1 2 0 2 2 2 1 2 0 1 1 0]


In [22]:
# 정확도 확인
acc = accuracy_score(y_test, y_pred)
acc

0.9666666666666667

In [24]:
# 오차 행렬 확인
confusion_matrix(y_test, y_pred)

array([[ 9,  0,  0],
       [ 0,  7,  1],
       [ 0,  0, 13]], dtype=int64)

In [26]:
# classification_report 사용
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.88      0.93         8
           2       0.93      1.00      0.96        13

    accuracy                           0.97        30
   macro avg       0.98      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

