* 자습 내용 기록

In [1]:
print(f'지금 온도는 {32.7495: 0.2f}입니다.')

지금 온도는  32.75입니다.


In [8]:
dic1 = {1:'a', 2:'b', 3:'c'}
dic2 = {'name':'python', 'age':'30', 'job':'programming'}
dic2.keys()
dic1.values()
dic1.items()

dic2['name'], dic2.get('name')

('python', 'python')

In [9]:
import numpy as np

In [11]:
ar1 = np.array([1,2,3,4])
ar1

array([1, 2, 3, 4])

In [18]:
np.random.randn(3)
np.random.randint(1,3,3)

array([2, 2, 2])

In [27]:
np.zeros(5)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
t_ar = np.arange(2, 10, 2).reshape(2,2)
t_ar

array([[2, 4],
       [6, 8]])

In [36]:
t_ar[0][0] = 0
t_ar

array([[0, 4],
       [6, 8]])

In [39]:
t_ar + 5
t_ar * 10

array([[ 0, 40],
       [60, 80]])

In [46]:
t_ar
t_ar.sum()
t_ar.mean()
t_ar.max()
t_ar.min()

0

In [47]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
ar1

array([[ 5,  7,  9],
       [-7, -6, 19],
       [ 6,  9, 11]])

In [57]:
ar1 == 0
ar1 = np.where(ar1 == 5, 0, ar1)
# 조건, True시 동작, False시 동작
ar1

array([[ 0,  7,  9],
       [-7, -6, 19],
       [ 6,  9, 11]])

In [87]:
ar1 = np.array([[5,7,9], [-3,-6,19], [6,4,11]])
ar1

array([[ 5,  7,  9],
       [-3, -6, 19],
       [ 6,  4, 11]])

In [88]:
ar1.sort(0)
ar1

array([[-3, -6,  9],
       [ 5,  4, 11],
       [ 6,  7, 19]])

In [93]:
ar1.sort(0)
ar1[::-1]

array([[ 6,  7, 19],
       [ 5,  4, 11],
       [-3, -6,  9]])

In [94]:
import pandas as pd

In [96]:
df1 = pd.read_csv('C:/Engineer_Big_Data_Analysis/DATAS/이기적데이터/df_sample.csv')
df1

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [100]:
df1['중간'].std()
df1['중간'].var()

112.71111111111112

In [102]:
df1['퀴즈'].value_counts()

18    3
10    2
14    2
20    1
12    1
16    1
Name: 퀴즈, dtype: int64

In [105]:
# 상관계수 빠르게
df1[['중간', '기말']].corr()

중간        기말
중간  1.000000  0.707196
기말  0.707196  1.000000

In [108]:
# 전체 상관계수
df1.corr()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_22332\3906147472.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.corr()


중간        기말       리포트        퀴즈
중간   1.000000  0.707196 -0.129388 -0.129388
기말   0.707196  1.000000  0.339210  0.339210
리포트 -0.129388  0.339210  1.000000  1.000000
퀴즈  -0.129388  0.339210  1.000000  1.000000

In [114]:
df2 = df1.copy()
df2

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [115]:
del df2['학번']
df2

중간  기말  리포트  퀴즈
0  90  95   20  20
1  82  83   18  18
2  80  78   18  18
3  78  75   10  10
4  93  91   12  12
5  71  75   16  16
6  60  80   18  18
7  72  65   14  14
8  65  65   14  14
9  85  78   10  10

In [116]:
df2.drop('퀴즈', axis=1)

중간  기말  리포트
0  90  95   20
1  82  83   18
2  80  78   18
3  78  75   10
4  93  91   12
5  71  75   16
6  60  80   18
7  72  65   14
8  65  65   14
9  85  78   10

In [118]:
df2.drop(1)

중간  기말  리포트  퀴즈
0  90  95   20  20
2  80  78   18  18
3  78  75   10  10
4  93  91   12  12
5  71  75   16  16
6  60  80   18  18
7  72  65   14  14
8  65  65   14  14
9  85  78   10  10